{"name": "Divide the Two number -- @1.4 ", "status": "broken", "statusDetails": {"message": "AttributeError: 'Context' object has no attribute 'first_number'\n", "trace": "  File \"C:\\Users\\Jatin-PC\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Jatin-PC\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"..\\steps\\steps.py\", line 50, in step_impl\n    if int(context.first_number) == int(context.second_number):\n  File \"C:\\Users\\Jatin-PC\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n"}, "steps": [{"name": "Given take the \"-2\" and \"-2\"", "status": "passed", "start": 1685414063785, "stop": 1685414063786}, {"name": "When verify if greater number between \"-2\" and \"-2\"", "status": "passed", "start": 1685414063787, "stop": 1685414063788}, {"name": "And divide greater with lower", "status": "passed", "start": 1685414063788, "stop": 1685414063789}, {"name": "Then Print the total result", "status": "passed", "start": 1685414063789, "stop": 1685414063790}, {"name": "And if both are same, return 0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Context' object has no attribute 'first_number'\n", "trace": "  File \"C:\\Users\\Jatin-PC\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Jatin-PC\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"..\\steps\\steps.py\", line 50, in step_impl\n    if int(context.first_number) == int(context.second_number):\n  File \"C:\\Users\\Jatin-PC\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n"}, "start": 1685414063790, "stop": 1685414063793}], "parameters": [{"name": "first_number", "value": "-2"}, {"name": "second_number", "value": "-2"}], "start": 1685414063783, "stop": 1685414063794, "uuid": "45e68ecc-2b33-4667-8a33-9edd0c83b1d7", "historyId": "6ecdf8f98a546e8e62eb9d41d21afdbe", "fullName": "Perform an division Feature: Divide the Two number", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Perform an division Feature"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}