{"name": "Divide the Two number -- @1.1 ", "status": "broken", "statusDetails": {"message": "AttributeError: 'Context' object has no attribute 'first_number'\n", "trace": "  File \"C:\\Users\\Jatin-PC\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Jatin-PC\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"..\\steps\\steps.py\", line 50, in step_impl\n    if int(context.first_number) == int(context.second_number):\n  File \"C:\\Users\\Jatin-PC\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n"}, "steps": [{"name": "Given take the \"4\" and \"2\"", "status": "passed", "start": 1685414063754, "stop": 1685414063754}, {"name": "When verify if greater number between \"4\" and \"2\"", "status": "passed", "start": 1685414063755, "stop": 1685414063755}, {"name": "And divide greater with lower", "status": "passed", "start": 1685414063756, "stop": 1685414063757}, {"name": "Then Print the total result", "status": "passed", "start": 1685414063757, "stop": 1685414063757}, {"name": "And if both are same, return 0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Context' object has no attribute 'first_number'\n", "trace": "  File \"C:\\Users\\Jatin-PC\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Jatin-PC\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"..\\steps\\steps.py\", line 50, in step_impl\n    if int(context.first_number) == int(context.second_number):\n  File \"C:\\Users\\Jatin-PC\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n"}, "start": 1685414063758, "stop": 1685414063760}], "parameters": [{"name": "first_number", "value": "4"}, {"name": "second_number", "value": "2"}], "start": 1685414063752, "stop": 1685414063761, "uuid": "6c5f503a-3ed7-47bc-b169-7fa8f071696d", "historyId": "6e2aac472d27d706bbeb76ea8d7ccc92", "fullName": "Perform an division Feature: Divide the Two number", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Perform an division Feature"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}